GlobalPlanner:
  ros__parameters:
    allow_unknown: false
    default_tolerance: 2.0
    use_dijkstra: false
    use_quadratic: true
    use_grid_path: true
    # visualize_potential: true
    # old_navfn_behavior: false
    # lethal_cost: 255
    # neutral_cost: 50
    # cost_factor: 3
    # publish_potential: true

NavfnROS:
  ros__parameters:
    allow_unknown: false